package us.tn.greatsmokey;

import jakarta.persistence.*;

/**
 * Represents a single cheeseburger entry in a user's quest log.
 * <p>
 * A {@code Burger} records one burger eaten at a particular {@link Restaurant},
 * along with a personal rating and freeform notes about the experience,
 * side, and drink that accompanied it. Each burger is linked to exactly one
 * restaurant via a many-to-one relationship, since a single restaurant may
 * have many logged burgers.
 */
@Entity
public class Burger {

   /** Primary key, auto-generated by the database. */
   @Id
   @GeneratedValue(strategy = GenerationType.IDENTITY)
   private Long id;

   /** The name of the burger (e.g. menu item name or a custom label). */
   private String name;

   /** The restaurant where this burger was eaten. */
   @ManyToOne
   @JoinColumn(name = "restaurant_id")
   private Restaurant restaurant;

   /** The user's personal rating for this burger. */
   private Double rating;

   /** Freeform notes about the burger (taste, texture, standout details, etc.). */
   private String notes;

   /** The side item that accompanied the burger, if any. */
   private String side;

   /** The drink that accompanied the burger, if any. */
   private String drink;
   
   /**
    * Default no-args constructor required by JPA.
    */
   public Burger() { }

   /**
    * Creates a new {@code Burger} with all fields populated.
    *
    * @param name the name of the burger
    * @param restaurant the restaurant where the burger was eaten
    * @param rating the user's rating for the burger
    * @param notes freeform notes about the burger
    * @param side the side item that accompanied the burger
    * @param drink the drink that accompanied the burger
    */
   public Burger(String name, Restaurant restaurant, Double rating, String notes, String side, String drink) {
      this.name = name;
      this.restaurant = restaurant;
      this.rating = rating;
      this.notes = notes;
      this.side = side;
      this.drink = drink;
   }

   /**
    * @return the database-generated id, or {@code null} if not yet persisted
    */
   public Long getId() {
      return id;
   }

   /**
    * @return the name of the burger
    */
   public String getName() {
      return name;
   }

   /**
    * @param name the name of the burger to set
    */
   public void setName(String name) {
      this.name = name;
   }

   /**
    * @return the restaurant where this burger was eaten
    */
   public Restaurant getRestaurant() {
      return restaurant;
   }

   /**
    * @param restaurant the restaurant to associate with this burger
    */
   public void setRestaurant(Restaurant restaurant) {
      this.restaurant = restaurant;
   }

   /**
    * @param restaurant the restaurant to associate with this burger
    */
   public Double getRating() {
      return rating;
   }

   /**
    * @param rating the rating to set for this burger
    */
   public void setRating(Double rating) {
      this.rating = rating;
   }

   /**
    * @return the notes recorded for this burger
    */
   public String getNotes() {
      return notes;
   }

   /**
    * @param notes the notes to set for this burger
    */
   public void setNotes(String notes) {
      this.notes = notes;
   }

   /**
    * @return the side
    */
   public String getSide() {
      return side;
   }

   /**
    * @param side the side to set
    */
   public void setSide(String side) {
      this.side = side;
   }

   /**
    * @return the drink
    */
   public String getDrink() {
      return drink;
   }

   /**
    * @param drink the drink to set
    */
   public void setDrink(String drink) {
      this.drink = drink;
   }

   /**
    * Returns a string representation of this burger, including all fields.
    * Primarily useful for logging and debugging.
    *
    * @return a string representation of this burger
    */
   @Override
   public String toString() {
   return "Burger [id=" + id + ", name=" + name + ", restaurant=" + restaurant + ", rating=" + rating + ", notes="
         + notes + ", side=" + side + ", drink=" + drink + "]";
   }
}