/**
 * 
 */
package us.tn.greatsmokey;

import jakarta.persistence.*;

/**
 * Represents a restaurant where cheeseburgers can be logged.
 * <p>
 * A {@code Restaurant} is not free text on a {@link Burger} — it's its own
 * entity, created automatically the first time a burger is logged there and
 * reused for every burger after. Restaurants can optionally be tagged with
 * a location, type, specialty, and U.S. state, laying the groundwork for
 * exploring regional variation in cheeseburgers.
 */
@Entity
@Table(name = "restaurant")
public class Restaurant {

   /** Primary key, auto-generated by the database. */
   @Id
   @GeneratedValue(strategy = GenerationType.IDENTITY)
   @Column(name = "restaurant_id")
   private Integer restaurantId;

   /** The restaurant's name. */
   private String name;
   
   /** A freeform description of where the restaurant is located. */
   private String location;
   
   /** The kind of establishment (e.g. diner, food truck, drive-in). */
   private String type;
   
   /** What the restaurant is known for, if anything. */
   private String specialty;
   
   /** The U.S. state the restaurant is in. */
   private String state;

   /**
    * Default no-args constructor required by JPA.
    */
   public Restaurant() { }
   
   /**
    * Creates a new {@code Restaurant} with just a name set, as happens when
    * a restaurant is first created on the fly from a new burger entry.
    *
    * @param restaurantName the name of the restaurant
    */
   public Restaurant(String restaurantName) { 
         this.name = restaurantName;
   }

   /**
    * @return the restaurantId
    */
   public Integer getRestaurantId() {
      return restaurantId;
   }

   /**
    * @param restaurantId the restaurantId to set
    */
   public void setRestaurantId(Integer restaurantId) {
      this.restaurantId = restaurantId;
   }

   /**
    * @return the name
    */
   public String getName() {
      return name;
   }

   /**
    * @param name the name to set
    */
   public void setName(String name) {
      this.name = name;
   }

   /**
    * @return the location
    */
   public String getLocation() {
      return location;
   }

   /**
    * @param location the location to set
    */
   public void setLocation(String location) {
      this.location = location;
   }

   /**
    * @return the type
    */
   public String getType() {
      return type;
   }

   /**
    * @param type the type to set
    */
   public void setType(String type) {
      this.type = type;
   }

   /**
    * @return the specialty
    */
   public String getSpecialty() {
      return specialty;
   }

   /**
    * @param specialty the specialty to set
    */
   public void setSpecialty(String specialty) {
      this.specialty = specialty;
   }

   /**
    * @return the state
    */
   public String getState() {
      return state;
   }

   /**
    * @param state the state to set
    */
   public void setState(String state) {
      this.state = state;
   }

   /**
    * Returns a string representation of this restaurant, including all fields.
    * Primarily useful for logging and debugging.
    *
    * @return a string representation of this restaurant
    */
   @Override
   public String toString() {
   return "Restaurant [restaurantId=" + restaurantId + ", name=" + name + ", location=" + location + ", type=" + type
         + ", specialty=" + specialty + ", state=" + state + "]";
   }
}
